apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backendreport.fullname" . }}
  labels:
    {{- include "backendreport.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.strategy.type }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "backendreport.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backendreport.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "backendreport.fullname" . }}-conf
                  key: port
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "backendreport.fullname" . }}-secret
                  key: db
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backendreport.fullname" . }}-conf
data:
  port: "{{ .Values.config.port }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backendreport.fullname" . }}-secret
type: Opaque
data:
  db: {{ .Values.secret.db | b64enc }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "backendreport.fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "backendreport.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}