apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (printf "%s-%s-service" .Release.Name .Chart.Name) }}
  # name: {{ .Release.Name }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}