apiVersion: apps/v1
kind: Deployment
metadata:
  name: sausage-postgres
  namespace: r-devops-magistracy-project-2sem-21475101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sausage-postgres
  template:
    metadata:
      labels:
        app: sausage-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sausage
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
