name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: ${{ secrets.NEXUS_HELM_REPO }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: r-devops-magistracy-project-2sem-21475101
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  # VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      outputs:
        DATE: ${{ steps.get-date.outputs.DATE }}
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-backend:latest
            build-args: |
              VERSION=${{ github.sha }}
        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-frontend:latest
        - name: Push Backend-report to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend-report/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/sausage-backend-report:latest
  
  add_helm_chart_to_nexus:
      name: Add Helm Chart To Nexus
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub
      outputs:
        chart_version: ${{ steps.versioning.outputs.NEW_VERSION }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install Helm with plugin
          run: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod +x get_helm.sh
            ./get_helm.sh --version v3.14.2
            helm plugin install https://github.com/chartmuseum/helm-push.git

        - name: Configure Helm repository
          run: |
            helm repo add chartmuseum "${{ env.NEXUS_HELM_REPO }}" \
              --username="${{ env.NEXUS_HELM_REPO_USER }}" \
              --password="${{ env.NEXUS_HELM_REPO_PASSWORD }}"
            helm repo update

        - name: Assign Helm chart version
          id: versioning
          run: |
            CHART_FILE="./sausage-store-chart/Chart.yaml"
            CURRENT_VERSION=$(grep "^version:" "$CHART_FILE" | awk '{print $2}')
            NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. '{$NF++; print}' OFS='.')
            echo "Updating chart version: $CURRENT_VERSION → $NEW_VERSION"
            sed -i "s/^version: .*/version: $NEW_VERSION/" "$CHART_FILE"
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

        - name: Packaging and pushing chart to Nexus
          run: |
            helm dependency update ./sausage-store-chart
            helm package ./sausage-store-chart --destination ./packaged-chart
            helm cm-push ./packaged-chart/sausage-store-*.tgz chartmuseum \
              --username="${{ env.NEXUS_HELM_REPO_USER }}" \
              --password="${{ env.NEXUS_HELM_REPO_PASSWORD }}" \
              --context-path="/repository/muxbyte93-sausage-store-project-sem2"
  
  deploy_helm_chart_to_kubernetes:
      name: Deploy Helm Chart To Kubernetes
      runs-on: ubuntu-latest
      needs: add_helm_chart_to_nexus

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.28.0'

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${KUBE_CONFIG}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install sausage-store sausage-store-chart \
            --namespace $SAUSAGE_STORE_NAMESPACE \
            --create-namespace \
            --set backend.image.repository=${{ secrets.DOCKER_USER }}/sausage-backend \
            --set frontend.image.repository=${{ secrets.DOCKER_USER }}/sausage-frontend \
            --set backendReport.image.repository=${{ secrets.DOCKER_USER }}/sausage-backend-report \
            --set backend.image.tag=latest \
            --set frontend.image.tag=latest \
            --set backendReport.image.tag=latest